import { GoogleGenAI } from "@google/genai"

export const maxDuration = 30

interface UserMovieData {
  likes: string[]
  watchlist: string[]
  seen: string[]
}

const SYSTEM_PROMPT = `You are "CineSensei", an expert movie critic and recommendation engine with deep knowledge of cinema history, current releases, and user preferences.

Your personality:
- Witty, engaging, and passionate about movies
- Concise but informative responses (keep under 200 words unless asked for details)
- Use movie references and cinema terminology naturally
- Be enthusiastic about great films and honest about poor ones

Your capabilities:
1. **Movie Recommendations**: Suggest films based on user preferences, mood, genre, or similar titles
2. **Movie Reviews**: Provide balanced, insightful reviews with pros/cons and ratings
3. **Movie Information**: Share details about cast, crew, plot, trivia, and behind-the-scenes facts
4. **Personalized Suggestions**: Use user's watchlist, likes, and viewing history for tailored recommendations
5. **Mood-Based Recommendations**: Suggest movies for specific moods, occasions, or viewing contexts

When giving recommendations:
- Consider user's viewing history to avoid duplicates
- Weight their liked movies heavily for similar suggestions
- Mention if they've already added something to their watchlist
- Provide 3-5 specific recommendations with brief reasons why

Always be helpful, entertaining, and genuinely passionate about cinema!`

function buildChatPrompt(messages: any[], userData: UserMovieData): string {
  const contextMessage =
    userData.likes.length > 0 || userData.watchlist.length > 0 || userData.seen.length > 0
      ? `User's Movie Profile:
🎬 Liked Movies: ${userData.likes.slice(0, 10).join(", ") || "None yet"}
📝 Watchlist: ${userData.watchlist.slice(0, 10).join(", ") || "Empty"}
✅ Recently Watched: ${userData.seen.slice(0, 10).join(", ") || "None logged"}

Use this profile to personalize recommendations and avoid suggesting movies they've already seen.`
      : `This user is new to the platform. Help them discover great movies and build their profile! Focus on popular, well-regarded films across different genres.`

  const conversationHistory = messages.map(msg =>
    `${msg.role === 'user' ? 'User' : 'Assistant'}: ${msg.content}`
  ).join('\n')

  return `${SYSTEM_PROMPT}\n\n${contextMessage}\n\nConversation:\n${conversationHistory}\n\nAssistant:`
}

export async function POST(req: Request) {
  try {
    const { messages, stream } = await req.json()

    if (!messages || !Array.isArray(messages)) {
      return Response.json({ error: "Invalid message format" }, { status: 400 })
    }

    if (!process.env.GEMINI_API_KEY) {
      throw new Error("GEMINI_API_KEY is not configured")
    }

    // Initialize Google GenAI client
    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY })

    // No user authentication - use empty movie profile
    const userMovieData = { likes: [], watchlist: [], seen: [] }

    // Build the conversation prompt
    const prompt = buildChatPrompt(messages, userMovieData)

    if (stream) {
      // Return streaming response
      return new Response(
        new ReadableStream({
          async start(controller) {
            try {
              // Generate content with Gemini
              const response = await ai.models.generateContent({
                model: "gemini-2.5-flash",
                contents: prompt,
                config: {
                  temperature: 0.7,
                  maxOutputTokens: 1024, // Increased to account for thinking tokens
                },
              })

              const content = response.text

              if (!content) {
                throw new Error("No response generated by Gemini")
              }

              // Simulate streaming by sending text in chunks
              const words = content.split(' ')
              for (let i = 0; i < words.length; i++) {
                const chunk = i === 0 ? words[i] : ' ' + words[i]
                controller.enqueue(new TextEncoder().encode(`data: ${JSON.stringify({ text: chunk })}\n\n`))

                // Add a small delay to simulate real-time generation
                await new Promise(resolve => setTimeout(resolve, 30))
              }

              controller.enqueue(new TextEncoder().encode(`data: ${JSON.stringify({ done: true })}\n\n`))
            } catch (error) {
              controller.enqueue(new TextEncoder().encode(`data: ${JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' })}\n\n`))
            } finally {
              controller.close()
            }
          },
        }),
        {
          headers: {
            'Content-Type': 'text/event-stream',
            'Cache-Control': 'no-cache',
            'Connection': 'keep-alive',
          },
        }
      )
    } else {
      // Non-streaming response (backward compatibility)
      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config: {
          temperature: 0.7,
          maxOutputTokens: 1024, // Increased to account for thinking tokens
        },
      })

      const content = response.text

      if (!content) {
        throw new Error("No response generated by Gemini")
      }

      return Response.json({ content })
    }
  } catch (error) {
    return Response.json(
      {
        error: "Sorry, I'm having trouble connecting to my AI brain right now. Please try again!",
      },
      { status: 500 }
    )
  }
}
