import { GoogleGenAI } from "@google/genai"

export const maxDuration = 30

export async function POST(req: Request) {
  try {
    const { title, stream } = await req.json()

    if (!title || typeof title !== "string") {
      return Response.json({ error: "Valid movie title is required" }, { status: 400 })
    }

    if (!process.env.GEMINI_API_KEY) {
      throw new Error("GEMINI_API_KEY is not configured")
    }

    // Initialize Google GenAI client
    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY })

    // Create the review prompt (shortened for faster generation)
    const prompt = `Write a concise, engaging movie review for "${title}". Include: brief plot, acting/direction analysis, what works/doesn't, who'd enjoy it, and rating. Keep it around 150-200 words.`

    if (stream) {
      // TRUE streaming response using Gemini's streaming API
      return new Response(
        new ReadableStream({
          async start(controller) {
            try {
              // Use streaming API for real-time token generation
              const streamResponse = await ai.models.generateContentStream({
                model: "gemini-2.5-flash",
                contents: prompt,
                config: {
                  temperature: 0.5, // Lower temperature for faster, more focused responses
                  maxOutputTokens: 2048, // Increased to prevent truncation with thinking tokens
                },
              })

              // Stream tokens as they arrive from Gemini
              for await (const chunk of streamResponse) {
                const text = chunk.text
                if (text) {
                  controller.enqueue(
                    new TextEncoder().encode(`data: ${JSON.stringify({ text })}\n\n`)
                  )
                }
              }

              controller.enqueue(
                new TextEncoder().encode(`data: ${JSON.stringify({ done: true })}\n\n`)
              )
            } catch (error) {
              const errorMessage = error instanceof Error ? error.message : 'Unknown error'
              controller.enqueue(
                new TextEncoder().encode(`data: ${JSON.stringify({ error: errorMessage })}\n\n`)
              )
            } finally {
              controller.close()
            }
          },
        }),
        {
          headers: {
            'Content-Type': 'text/event-stream',
            'Cache-Control': 'no-cache',
            'Connection': 'keep-alive',
          },
        }
      )
    } else {
      // Non-streaming response (backward compatibility)
      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config: {
          temperature: 0.5,
          maxOutputTokens: 2048, // Increased to prevent truncation with thinking tokens
        },
      })

      const review = response.text

      if (!review) {
        throw new Error("No review generated by Gemini")
      }

      return Response.json({ review })
    }
  } catch (err) {
    return Response.json(
      {
        error:
          "I couldn't generate a review right now. My AI circuits are a bit scrambled! Please try again in a moment.",
      },
      { status: 500 },
    )
  }
}
